export const stations: Array<string> = [
    "Abfaltersbach, Bahnhof",
    "Absdorf-Hippersdorf, Bahnhof",
    "Achau, Bahnhof",
    "Admont, Bahnhof",
    "Aigen-Schlägl, Bahnhof",
    "Allentsteig, Bahnhof",
    "Altmünster am Traunsee, Bahnhof",
    "Altpinkafeld, Bahnhof",
    "Amstetten, Bahnhof",
    "Andorf, Bahnhof",
    "Angern, Bahnhof",
    "Antiesenhofen, Bahnhof",
    "Arbing, Bahnhof",
    "Ardning, Bahnhof",
    "Arnoldstein, Bahnhof",
    "Aschach an der Donau, Bahnhof",
    "Aspang, Bahnhof",
    "Attnang-Puchheim, Bahnhof",
    "Aurachkirchen, Bahnhof",
    "Ausschlag-Zöbern, Bahnhof",
    "Bad Aussee, Bahnhof",
    "Bad Deutsch Altenburg, Bahnhof",
    "Bad Erlach, Bahnhof",
    "Bad Fischau Brunn, Bahnhof",
    "Bad Gastein, Bahnhof",
    "Bad Goisern, Bahnhof",
    "Bad Hofgastein, Bahnhof",
    "Bad Ischl, Bahnhof",
    "Bad Mitterndorf, Bahnhof",
    "Bad Pirawarth, Bahnhof",
    "Bad Radkersburg, Bahnhof",
    "Bad Sauerbrunn, Bahnhof",
    "Bad Schallerbach-Wallern, Bahnhof",
    "Bad St. Leonhard, Bahnhof",
    "Bad Vöslau, Bahnhof",
    "Baumgartenberg, Bahnhof",
    "Berndorf Fabrik, Bahnhof",
    "Bernhardsthal, Bahnhof",
    "Bierbaum, Bahnhof",
    "Bischofshofen, Bahnhof",
    "Bleiburg, Bahnhof",
    "Bludenz, Bahnhof",
    "Bockfließ, Bahnhof",
    "Böckstein, Bahnhof",
    "Böheimkirchen, Bahnhof",
    "Braunau am Inn, Bahnhof",
    "Bregenz, Bahnhof",
    "Breitenschützing, Bahnhof",
    "Breitenstein, Bahnhof",
    "Brixlegg, Bahnhof",
    "Bruck a. d. Leitha, Bahnhof",
    "Bruck a. d. Mur, Bahnhof",
    "Bruck-Fusch, Bahnhof",
    "Brunn Maria Enzersdorf, Bahnhof",
    "Dellach im Drautal, Bahnhof",
    "Deutsch Wagram, Bahnhof",
    "Deutschkreutz, Bahnhof",
    "Dölsach, Bahnhof",
    "Dorfgastein, Bahnhof",
    "Dornbirn, Bahnhof",
    "Drösing, Bahnhof",
    "Dürnkrut, Bahnhof",
    "Eben im Pongau, Bahnhof",
    "Ebenfurth, Bahnhof",
    "Ebensee, Bahnhof",
    "Ebreichsdorf, Bahnhof",
    "Edlitz-Grimmenstein, Bahnhof",
    "Eferding, Bahnhof",
    "Eggenburg, Bahnhof",
    "Ehrwald-Zugspitzbahn, Bahnhof",
    "Eichberg, Bahnhof",
    "Eis-Ruden, Bahnhof",
    "Eisenstadt Schule, Bahnhof",
    "Eisenstadt, Bahnhof",
    "Enns, Bahnhof",
    "Enzersdorf bei Staatz, Bahnhof",
    "Enzesfeld-Lindabrunn, Bahnhof",
    "Erlauf, Bahnhof",
    "Ernstbrunn, Bahnhof",
    "Ernsthofen, Bahnhof",
    "Etsdorf-Straß, Bahnhof",
    "Faak am See, Bahnhof",
    "Fehring, Bahnhof",
    "Feldbach, Bahnhof",
    "Feldkirch, Bahnhof",
    "Feldkirchen in Kärnten, Bahnhof",
    "Felixdorf, Bahnhof",
    "Fels, Bahnhof",
    "Fentsch-St. Lorenzen, Bahnhof",
    "Feuerwerksanstalt, Bahnhof",
    "Fischamend, Bahnhof",
    "Flughafen Wien (VIE), Bahnhof",
    "Föderlach, Bahnhof",
    "Frankenmarkt, Bahnhof",
    "Frantschach-St. Gertraud, Bahnhof",
    "Frastanz, Bahnhof",
    "Frättingsdorf, Bahnhof",
    "Freistadt, Bahnhof",
    "Friedberg, Bahnhof",
    "Friedburg , Bahnhof",
    "Friesach, Bahnhof",
    "Fritzens-Wattens, Bahnhof",
    "Frohnleiten, Bahnhof",
    "Fürnitz, Bahnhof",
    "Fürstenfeld, Bahnhof",
    "Furth-Palt, Bahnhof",
    "Gaisbach-Wartberg, Bahnhof",
    "Gaishorn, Bahnhof",
    "Gänserndorf, Bahnhof",
    "Gars-Thunau, Bahnhof",
    "Garsten, Bahnhof",
    "Gattendorf, Bahnhof",
    "Gerasdorf, Bahnhof",
    "Glanegg, Bahnhof",
    "Gleisdorf, Bahnhof",
    "Gloggnitz, Bahnhof",
    "Gmünd N.Ö., Bahnhof",
    "Gmunden, Bahnhof",
    "Göllersdorf, Bahnhof",
    "Golling-Abtenau, Bahnhof",
    "Göpfritz, Bahnhof",
    "Görtschach-Förolach, Bahnhof",
    "Gosdorf, Bahnhof",
    "Götzendorf, Bahnhof",
    "Götzis, Bahnhof",
    "Grafendorf, Bahnhof",
    "Grafenstein, Bahnhof",
    "Gramatneusiedl, Bahnhof",
    "Gratwein-Gratkorn, Bahnhof",
    "Graz Hbf, Bahnhof",
    "Graz Ostbahnhof-Messe, Bahnhof",
    "Graz Puntigam, Bahnhof",
    "Graz Stadion Liebenau, Bahnhof",
    "Greifenburg-Weißensee, Bahnhof",
    "Grein Stadt, Bahnhof",
    "Grein-Bad Kreuzen, Bahnhof",
    "Grieskirchen-Gallspach, Bahnhof",
    "Gröbming, Bahnhof",
    "Groß Engersdorf, Bahnhof",
    "Groß Schweinbarth, Bahnhof",
    "Großendorf, Bahnhof",
    "Großweikersdorf, Bahnhof",
    "Grünau im Almtal, Bahnhof",
    "Grünbach am Schneeberg, Bahnhof",
    "Gstatterboden im Nationalpark, Bahnhof",
    "Gummern, Bahnhof",
    "Gunskirchen, Bahnhof",
    "Guntersdorf, Bahnhof",
    "Gurten, Bahnhof",
    "Gutenstein, Bahnhof",
    "Hadersdorf am Kamp, Bahnhof",
    "Haiding, Bahnhof",
    "Hainburg a. d. Donau Kulturfabrik, Bahnhof",
    "Hainfeld, Bahnhof",
    "Halbenrain, Bahnhof",
    "Hall in Tirol, Bahnhof",
    "Hallein, Bahnhof",
    "Hallwang-Elixhausen, Bahnhof",
    "Handelskai, Bahnhof",
    "Hartberg, Bahnhof",
    "Haslach, Bahnhof",
    "Haus, Bahnhof",
    "Hausleiten, Bahnhof",
    "Hausruck, Bahnhof",
    "Hengsberg, Bahnhof",
    "Hennersdorf, Bahnhof",
    "Hermagor, Bahnhof",
    "Herzogenburg, Bahnhof",
    "Hetzmannsdorf-Wullersdorf, Bahnhof",
    "Hieflau, Bahnhof",
    "Hilm-Kematen, Bahnhof",
    "Himberg, Bahnhof",
    "Hinterstoder, Bahnhof",
    "Hochfilzen, Bahnhof",
    "Hochzirl, Bahnhof",
    "Hohenau, Bahnhof",
    "Hohenems, Bahnhof",
    "Hollabrunn, Bahnhof",
    "Hopfgarten, Bahnhof",
    "Horn, Bahnhof",
    "Hörsching, Bahnhof",
    "Hötzelsdorf-Geras, Bahnhof",
    "Hüttau Terminal, Bahnhof",
    "Imst-Pitztal, Bahnhof",
    "Innsbruck Hbf, Bahnhof",
    "Innsbruck Hötting, Bahnhof",
    "Innsbruck Westbf, Bahnhof",
    "Irnfritz, Bahnhof",
    "Jenbach, Bahnhof",
    "Jennersdorf, Bahnhof",
    "Judenburg, Bahnhof",
    "Kainisch, Bahnhof",
    "Kaiserebersdorf, Bahnhof",
    "Kalsdorf, Bahnhof",
    "Kalwang, Bahnhof",
    "Kapfenberg, Bahnhof",
    "Kefermarkt, Bahnhof",
    "Kematen a. d. Krems, Bahnhof",
    "Kindberg, Bahnhof",
    "Kirchberg am Wagram, Bahnhof",
    "Kirchberg in Tirol, Bahnhof",
    "Kirchbichl, Bahnhof",
    "Kirchdorf a. d. Krems, Bahnhof",
    "Kirchstetten, Bahnhof",
    "Kittsee, Bahnhof",
    "Kitzbühel, Bahnhof",
    "Klagenfurt Hbf, Bahnhof",
    "Klagenfurt Ostbf, Bahnhof",
    "Klaus, Bahnhof",
    "Kleblach-Lind, Bahnhof",
    "Kleinreifling, Bahnhof",
    "Klosterneuburg-Weidling, Bahnhof",
    "Knittelfeld, Bahnhof",
    "Kolbnitz, Bahnhof",
    "Korneuburg, Bahnhof",
    "Kraubath, Bahnhof",
    "Krems a. d. Donau, Bahnhof",
    "Kremsmünster, Bahnhof",
    "Krieglach, Bahnhof",
    "Kritzendorf, Bahnhof",
    "Krumpendorf, Bahnhof",
    "Kufstein, Bahnhof",
    "Kundl, Bahnhof",
    "Laa a. d. Thaya Stadt, Bahnhof",
    "Laakirchen (Gf), Bahnhof",
    "Ladendorf, Bahnhof",
    "Lahrndorf, Bahnhof",
    "Lambach, Bahnhof",
    "Landeck - Zams, Bahnhof",
    "Langen am Arlberg, Bahnhof",
    "Langenlois, Bahnhof",
    "Langwies, Bahnhof",
    "Lanzendorf-Rannersdorf, Bahnhof",
    "Lanzenkirchen, Bahnhof",
    "Laßnitzhöhe, Bahnhof",
    "Laßnitzthal, Bahnhof",
    "Launsdorf-Hochosterwitz, Bahnhof",
    "Laxenburg-Biedermannsdf, Bahnhof",
    "Ledenitzen, Bahnhof",
    "Leibnitz, Bahnhof",
    "Lend, Bahnhof",
    "Lenzing, Bahnhof",
    "Leoben Hbf, Bahnhof",
    "Leobersdorf, Bahnhof",
    "Lermoos, Bahnhof",
    "Lienz, Bahnhof",
    "Liezen, Bahnhof",
    "Lilienfeld, Bahnhof",
    "Limberg-Maissau, Bahnhof",
    "Linz Franckstraße, Bahnhof",
    "Linz Hbf, Bahnhof",
    "Linz Urfahr, Bahnhof",
    "Linz Wegscheid, Bahnhof",
    "Lochau-Hörbranz, Bahnhof",
    "Loipersbach-Schattendorf, Bahnhof",
    "Loosdorf, Bahnhof",
    "Losenstein, Bahnhof",
    "Ludesch, Bahnhof",
    "Lungitz, Bahnhof",
    "Lustenau, Bahnhof",
    "Mallnitz-Obervellach, Bahnhof",
    "Mandling, Bahnhof",
    "Marchegg, Bahnhof",
    "Marchtrenk, Bahnhof",
    "Marein-St. Lorenzen, Bahnhof",
    "Maria Ellend a. d. Donau, Bahnhof",
    "Maria Ellend-Haslau, Bahnhof",
    "Maria Lanzendorf, Bahnhof",
    "Maria Saal, Bahnhof",
    "Mariahof-St. Lambrecht, Bahnhof",
    "Matrei, Bahnhof",
    "Mattersburg, Bahnhof",
    "Mattighofen, Bahnhof",
    "Mauerkirchen, Bahnhof",
    "Mautern, Bahnhof",
    "Mauthausen, Bahnhof",
    "Micheldorf, Bahnhof",
    "Mining, Bahnhof",
    "Mistelbach, Bahnhof",
    "Mitterdorf Veitsch, Bahnhof",
    "Mitterweißenbach, Bahnhof",
    "Mixnitz Bärenschützklamm, Bahnhof",
    "Mödling, Bahnhof",
    "Möllbrücke-Sachsenburg, Bahnhof",
    "Moosbierbaum-Heiligeneich, Bahnhof",
    "Münchendorf, Bahnhof",
    "Munderfing, Bahnhof",
    "Mureck, Bahnhof",
    "Mürzzuschlag, Bahnhof",
    "Nettingsdorf, Bahnhof",
    "Neubau-Kreuzstetten, Bahnhof",
    "Neudörfl, Bahnhof",
    "Neufelden, Bahnhof",
    "Neuhaus-Niederwaldkirchen, Bahnhof",
    "Neuhofen a. d. Krems, Bahnhof",
    "Neulengbach, Bahnhof",
    "Neumarkt in Steiermark, Bahnhof",
    "Neumarkt Kallham, Bahnhof",
    "Neunkirchen NÖ, Bahnhof",
    "Neusiedl am See, Bahnhof",
    "Nickelsdorf, Bahnhof",
    "Niklasdorf, Bahnhof",
    "Nötsch, Bahnhof",
    "Obdach, Bahnhof",
    "Ober Piesting, Bahnhof",
    "Oberdrauburg, Bahnhof",
    "Obereggendorf, Bahnhof",
    "Oberland, Bahnhof",
    "Obernberg-Altheim, Bahnhof",
    "Obersdorf, Bahnhof",
    "Obertraun-Dachsteinhöhlen, Bahnhof",
    "Oberwart, Bahnhof",
    "Oberweiden, Bahnhof",
    "Öblarn, Bahnhof",
    "Oed, Bahnhof",
    "Oepping, Bahnhof",
    "Ortmann, Bahnhof",
    "Ossiach-Bodensdorf, Bahnhof",
    "Ottensheim, Bahnhof",
    "Ottnang-Wolfsegg, Bahnhof",
    "Ötztal, Bahnhof",
    "Parndorf, Bahnhof",
    "Paudorf, Bahnhof",
    "Payerbach-Reichenau, Bahnhof",
    "Peggau Deutschfeistritz, Bahnhof",
    "Penk, Bahnhof",
    "Perg, Bahnhof",
    "Pernegg, Bahnhof",
    "Pernitz-Muggendorf, Bahnhof",
    "Petronell-Carnuntum, Bahnhof",
    "Pettenbach, Bahnhof",
    "Pichl, Bahnhof",
    "Piesting, Bahnhof",
    "Pill-Vomperbach, Bahnhof",
    "Pinkafeld Schule, Bahnhof",
    "Pinkafeld, Bahnhof",
    "Pitten, Bahnhof",
    "Plank am Kamp, Bahnhof",
    "Pöchlarn, Bahnhof",
    "Pöham, Bahnhof",
    "Pörtschach am Wörthersee, Bahnhof",
    "Pottenbrunn, Bahnhof",
    "Pottenstein a. d. Triesting, Bahnhof",
    "Pram-Haag, Bahnhof",
    "Pregarten, Bahnhof",
    "Prinzersdorf, Bahnhof",
    "Puchberg am Schneeberg, Bahnhof",
    "Puchenau West, Bahnhof",
    "Purbach am Neusiedlersee, Bahnhof",
    "Pürbach-Schrems, Bahnhof",
    "Purgstall, Bahnhof",
    "Pusarnitz, Bahnhof",
    "Raasdorf, Bahnhof",
    "Radstadt, Bahnhof",
    "Ramingdorf-Haidershofen, Bahnhof",
    "Rankweil, Bahnhof",
    "Redl-Zipf, Bahnhof",
    "Regelsbrunn, Bahnhof",
    "Reichraming, Bahnhof",
    "Reith, Bahnhof",
    "Rekawinkel, Bahnhof",
    "Retz, Bahnhof",
    "Reutte in Tirol, Bahnhof",
    "Ried im Innkreis, Bahnhof",
    "Riedau, Bahnhof",
    "Rohr-Bad Hall, Bahnhof",
    "Rohrbach Berg, Bahnhof",
    "Rohrbach-Vorau, Bahnhof",
    "Roppen, Bahnhof",
    "Rosenbach, Bahnhof",
    "Rosenburg, Bahnhof",
    "Rothenthurn, Bahnhof",
    "Rottenegg, Bahnhof",
    "Rottenmann, Bahnhof",
    "Rückersdorf-Harmannsdorf, Bahnhof",
    "Saalfelden, Bahnhof",
    "Salzburg Aigen, Bahnhof",
    "Salzburg Aiglhof, Bahnhof",
    "Salzburg Hbf, Bahnhof",
    "Salzburg Mülln-Altstadt, Bahnhof",
    "Sarmingstein, Bahnhof",
    "Sattendorf, Bahnhof",
    "Sattledt, Bahnhof",
    "Saxen, Bahnhof",
    "Schärding, Bahnhof",
    "Scharnitz, Bahnhof",
    "Scharnstein-Mühldorf, Bahnhof",
    "Schauersberg, Bahnhof",
    "Scheibbs, Bahnhof",
    "Scheiblingkirchen-Warth, Bahnhof",
    "Scheifling, Bahnhof",
    "Schladming, Bahnhof",
    "Schleinbach, Bahnhof",
    "Schönberg am Kamp, Bahnhof",
    "Schönfeld-Lassee, Bahnhof",
    "Schönwies, Bahnhof",
    "Schrambach, Bahnhof",
    "Schützen am Gebirge, Bahnhof",
    "Schwanenstadt, Bahnhof",
    "Schwarzach-St. Veit, Bahnhof",
    "Schwarzenau, Bahnhof",
    "Schwaz, Bahnhof",
    "Schwechat, Bahnhof",
    "Schwertberg, Bahnhof",
    "Sebersdorf, Bahnhof",
    "Seebenstein, Bahnhof",
    "Seefeld in Tirol, Bahnhof",
    "Seekirchen am Wallersee, Bahnhof",
    "Selzthal, Bahnhof",
    "Semmering, Bahnhof",
    "Siebenbrunn-Leopoldsdorf, Bahnhof",
    "Sierndorf, Bahnhof",
    "Sigmundsherberg, Bahnhof",
    "Sillian, Bahnhof",
    "Silz, Bahnhof",
    "Sinnersdorf, Bahnhof",
    "Söchau, Bahnhof",
    "Spielfeld-Straß, Bahnhof",
    "Spital am Pyhrn, Bahnhof",
    "Spital am Semmering, Bahnhof",
    "Spittal-Millstättersee, Bahnhof",
    "St. Andrä im Lavanttal, Bahnhof",
    "St. Andrä-Wördern, Bahnhof",
    "St. Anton am Arlberg, Bahnhof",
    "St. Georgen a. d. Gusen, Bahnhof",
    "St. Johann im Pongau, Bahnhof",
    "St. Johann in Tirol, Bahnhof",
    "St. Martin im Innkreis, Bahnhof",
    "St. Martin-Sittich, Bahnhof",
    "St. Michael, Bahnhof",
    "St. Nikola-Struden, Bahnhof",
    "St. Peter-Seitenstetten, Bahnhof",
    "St. Pölten Hbf, Bahnhof",
    "St. Stefan im Lavanttal, Bahnhof",
    "St. Stefan-Vorderberg, Bahnhof",
    "St. Valentin, Bahnhof",
    "St. Veit a. d. Glan Westbf, Bahnhof",
    "St. Veit a. d. Glan, Bahnhof",
    "St. Veit a. d. Gölsen, Bahnhof",
    "St.Paul, Bahnhof",
    "St.Pölten Alpenbf, Bahnhof",
    "Stadl-Paura, Bahnhof",
    "Stainach-Irdning, Bahnhof",
    "Stams, Bahnhof",
    "Statzendorf, Bahnhof",
    "Steeg-Gosau, Bahnhof",
    "Steinach in Tirol, Bahnhof",
    "Steinbachbrücke, Bahnhof",
    "Steindorf am Ossiacher See, Bahnhof",
    "Steindorf b.Strasswalchen, Bahnhof",
    "Steinfeld im Drautal, Bahnhof",
    "Steinhaus bei Wels, Bahnhof",
    "Stetten, Bahnhof",
    "Steyr, Bahnhof",
    "Steyregg, Bahnhof",
    "Steyrling, Bahnhof",
    "Stiefern, Bahnhof",
    "Stockerau, Bahnhof",
    "Straßwalchen, Bahnhof",
    "Studenzen-Fladnitz, Bahnhof",
    "Summerau, Bahnhof",
    "Tainach-Stein, Bahnhof",
    "Takern-St. Margarethen, Bahnhof",
    "Tattendorf, Bahnhof",
    "Tauchen-Schaueregg, Bahnhof",
    "Taufkirchen a. d. Pram, Bahnhof",
    "Tauplitz, Bahnhof",
    "Taxenbach-Rauris, Bahnhof",
    "Telfs-Pfaffenhofen, Bahnhof",
    "Terfens-Weer, Bahnhof",
    "Ternberg, Bahnhof",
    "Ternitz, Bahnhof",
    "Thal, Bahnhof",
    "Thalheim-Pöls, Bahnhof",
    "Thörl-Maglern, Bahnhof",
    "Timelkam, Bahnhof",
    "Traisen, Bahnhof",
    "Traiskirchen Aspangbahn, Bahnhof",
    "Traismauer, Bahnhof",
    "Traun, Bahnhof",
    "Traunkirchen, Bahnhof",
    "Traxenbichl, Bahnhof",
    "Treibach-Althofen, Bahnhof",
    "Trieben, Bahnhof",
    "Tulln a. d. Donau, Bahnhof",
    "Tulln Stadt, Bahnhof",
    "Tullnerbach-Preßbaum, Bahnhof",
    "Tullnerfeld, Bahnhof",
    "Ulmerfeld-Hausmening, Bahnhof",
    "Unter Purkersdorf, Bahnhof",
    "Unterhart, Bahnhof",
    "Unzmarkt, Bahnhof",
    "Velden am Wörthersee, Bahnhof",
    "Viechtwang, Bahnhof",
    "Viehofen, Bahnhof",
    "Villach Hbf Autovlst, Bahnhof",
    "Villach Hbf, Bahnhof",
    "Villach St. Ruprecht, Bahnhof",
    "Villach Westbf, Bahnhof",
    "Vitis, Bahnhof",
    "Vöcklabruck, Bahnhof",
    "Vöcklamarkt, Bahnhof",
    "Voitsdorf, Bahnhof",
    "Völkermarkt-Kühnsdorf, Bahnhof",
    "Völs, Bahnhof",
    "Waidhofen a. d. Ybbs, Bahnhof",
    "Wald am Schoberpaß, Bahnhof",
    "Waldegg, Bahnhof",
    "Wampersdorf, Bahnhof",
    "Wartberg a.d.Krems, Bahnhof",
    "Wartberg im Mürztal, Bahnhof",
    "Weissenbach-Neuhaus, Bahnhof",
    "Weißenbach-St. Gallen, Bahnhof",
    "Weitersfeld a. d. Mur, Bahnhof",
    "Weizelsdorf, Bahnhof",
    "Wels Hbf, Bahnhof",
    "Wels Lb, Bahnhof",
    "Werfen, Bahnhof",
    "Werndorf, Bahnhof",
    "Wernstein, Bahnhof",
    "Wettmannstätten, Bahnhof",
    "Wetzleinsdorf, Bahnhof",
    "Weyer, Bahnhof",
    "Wien Blumental, Bahnhof",
    "Wien Floridsdorf, Bahnhof",
    "Wien Franz-Josefs-Bahnhof, Bahnhof",
    "Wien Grillgasse, Bahnhof",
    "Wien Hauptbahnhof (Bahnsteige 1-2), Bahnhof",
    "Wien Hauptbahnhof, Bahnhof",
    "Wien Heiligenstadt, Bahnhof",
    "Wien Hernals, Bahnhof",
    "Wien Hütteldorf, Bahnhof",
    "Wien Jedlersdorf, Bahnhof",
    "Wien Leopoldau, Bahnhof",
    "Wien Liesing, Bahnhof",
    "Wien Mitte, Bahnhof",
    "Wien Nußdorf, Bahnhof",
    "Wien Ottakring, Bahnhof",
    "Wien Penzing, Bahnhof",
    "Wien Praterstern, Bahnhof",
    "Wien Süßenbrunn, Bahnhof",
    "Wien Westbahnhof, Bahnhof",
    "Wien Zentralfriedhof, Bahnhof",
    "Wiener Neustadt Hbf, Bahnhof",
    "Wieselburg a. d. Erlauf, Bahnhof",
    "Wildon, Bahnhof",
    "Wilhelmsburg a. d. Traisen, Bahnhof",
    "Willendorf, Bahnhof",
    "Windischgarsten, Bahnhof",
    "Winzendorf, Bahnhof",
    "Wittmannsdorf, Bahnhof",
    "Wolfsberg, Bahnhof",
    "Wolfsthal, Bahnhof",
    "Wolfurt, Bahnhof",
    "Wolkersdorf, Bahnhof",
    "Wöllersdorf, Bahnhof",
    "Wörgl Hbf, Bahnhof",
    "Ybbs a. d. Donau, Bahnhof",
    "Zell am See, Bahnhof",
    "Zellerndorf, Bahnhof",
    "Zeltweg, Bahnhof",
    "Ziersdorf, Bahnhof",
    "Zirl, Bahnhof",
    "Zurndorf, Bahnhof",
];